In [1]:
import numpy as np
import pandas as pd

Long VS Wide Data

In [5]:
#melt
pd.DataFrame({'cse':[120]}).melt()

  variable  value
0      cse    120

In [8]:
pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]}).melt(var_name='branch',value_name='num_students')

  branch  num_students
0    cse           120
1    ece           100
2   mech            50

In [15]:
pd.DataFrame(
    {
        'branch':['cse','ece','mech'],
        '2020':[100,150,60],
        '2021':[120,130,80],
        '2022':[150,140,70]
    }
).melt(id_vars=['branch'],var_name='year',value_name='students')

  branch  year  students
0    cse  2020       100
1    ece  2020       150
2   mech  2020        60
3    cse  2021       120
4    ece  2021       130
5   mech  2021        80
6    cse  2022       150
7    ece  2022       140
8   mech  2022        70

In [54]:
# melt -> real world example
death = pd.read_csv('time_series_covid19_deaths_global.csv')
confirm = pd.read_csv('time_series_covid19_confirmed_global.csv')

In [55]:
death.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [57]:
death = death.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_deaths')
confirm = confirm.melt(id_vars=['Province/State','Country/Region','Lat','Long'],var_name='date',value_name='num_cases')

In [58]:
death.head()

  Province/State Country/Region       Lat       Long     date  num_deaths
0            NaN    Afghanistan  33.93911  67.709953  1/22/20           0
1            NaN        Albania  41.15330  20.168300  1/22/20           0
2            NaN        Algeria  28.03390   1.659600  1/22/20           0
3            NaN        Andorra  42.50630   1.521800  1/22/20           0
4            NaN         Angola -11.20270  17.873900  1/22/20           0

In [59]:
confirm.head()

  Province/State Country/Region       Lat       Long     date  num_cases
0            NaN    Afghanistan  33.93911  67.709953  1/22/20          0
1            NaN        Albania  41.15330  20.168300  1/22/20          0
2            NaN        Algeria  28.03390   1.659600  1/22/20          0
3            NaN        Andorra  42.50630   1.521800  1/22/20          0
4            NaN         Angola -11.20270  17.873900  1/22/20          0

In [60]:
confirm.merge(death,on=['Province/State','Country/Region','Lat','Long','date'])[['Country/Region','date','num_cases','num_deaths']]

              Country/Region     date  num_cases  num_deaths
0                Afghanistan  1/22/20          0           0
1                    Albania  1/22/20          0           0
2                    Algeria  1/22/20          0           0
3                    Andorra  1/22/20          0           0
4                     Angola  1/22/20          0           0
...                      ...      ...        ...         ...
311248    West Bank and Gaza   1/2/23     703228        5708
311249  Winter Olympics 2022   1/2/23        535           0
311250                 Yemen   1/2/23      11945        2159
311251                Zambia   1/2/23     334661        4024
311252              Zimbabwe   1/2/23     259981        5637

[311253 rows x 4 columns]