Series from lists

In [3]:
# string 
import numpy as np
import pandas as pd
country = ["India","Pakistan","china","Iran","USA"]
pd.Series(country)

0       India
1    Pakistan
2       china
3        Iran
4         USA
dtype: object

In [4]:
#integers
runs = [13,24,56,78,100]
pd.Series(runs)

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [5]:
# custom index
marks = [65,78,75,80]
subjects = ["java","DS","python","sql"]

pd.Series(marks,index = subjects)

java      65
DS        78
python    75
sql       80
dtype: int64

In [7]:
#setting a name

marks = (pd.Series(marks,index = subjects,name = "kim ke marks"))
print(marks)

java      65
DS        78
python    75
sql       80
Name: kim ke marks, dtype: int64

Series from dict

In [31]:
marks_series = {
    "maths" : 67,
    "English" :78,
    "Science" :89,
    "history" :88
}

marks_series = pd.Series(marks,name = "jungkook ke marks")
marks_series

maths      67
English    78
Science    89
history    88
Name: jungkook ke marks, dtype: int64

Series Attributes

In [12]:
# size
marks_series.size

4

In [32]:
# name
marks_series.name

'jungkook ke marks'

In [33]:
#dtype
marks_series.dtype

dtype('int64')

In [36]:
#is_unique
marks_series.is_unique
pd.Series([1,1,2,3,4,5,6]).is_unique

False

In [39]:
type(runs.index)

builtin_function_or_method

In [40]:
#values
marks_series.values

array([67, 78, 89, 88])

In [72]:
#csv
# with one col
subs = pd.read_csv("subs.csv")
subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [71]:
type(subs)

pandas.core.frame.DataFrame

In [80]:
#with 2 cols
vk =(pd.read_csv("kohli_ipl.csv",index_col = "match_no"))
vk

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

Series Methods

In [77]:
# head and tail
subs.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [81]:
vk.head(3)

          runs
match_no
1            1
2           23
3           13

In [82]:
vk.tail()

          runs
match_no
211          0
212         20
213         73
214         25
215          7

In [83]:
vk.sample()

          runs
match_no
67           3

In [89]:
vk

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [97]:
vk.sort_values(by="runs")

          runs
match_no
87           0
211          0
207          0
206          0
91           0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [99]:
vk.sort_values(by="runs",inplace=True)

In [100]:
vk

          runs
match_no
87           0
211          0
207          0
206          0
91           0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

Series Maths Methods

In [102]:
vk.count()

runs    215
dtype: int64

In [104]:
subs.sum()

Subscribers gained    49510
dtype: int64

In [105]:
subs.mean()

Subscribers gained    135.643836
dtype: float64

In [106]:
vk.median()

runs    24.0
dtype: float64

In [108]:
subs.mode()

   Subscribers gained
0                 105

In [109]:
subs.std()

Subscribers gained    62.675023
dtype: float64

In [113]:
print(vk.var())

runs    688.002478
dtype: float64

In [114]:
subs.min()

Subscribers gained    33
dtype: int64

In [115]:
vk.describe()

             runs
count  215.000000
mean    30.855814
std     26.229801
min      0.000000
25%      9.000000
50%     24.000000
75%     48.000000
max    113.000000

Series Indexing/Slicing

In [120]:
#integer indexing
x = pd.Series([12,13,14,35,46,57,58,79,9])
x[6]

np.int64(58)

In [129]:
vk[5:8]

          runs
match_no
93           0
8            0
130          0

In [145]:
num = pd.Series([1,2,3,4,5])

In [148]:
num[0]=4
num

0    4
1    2
2    3
3    4
4    5
dtype: int64